{% set name = "birdsong-recognition-dataset" %}
{% set version = "0.3.2.post1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/birdsong-recognition-dataset-{{ version }}.tar.gz
  sha256: 7d3378b07623c0220543501aa9c8e52cb2602963ac23abe6ba9ec563cc3957f5

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - flit-core
  run:
    - numpy >=1.18.1
    - python >={{ python_min }}

test:
  imports:
    - birdsongrec
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/birdsong-recognition-dataset/
  summary: 'Functions for working with this data repository: https://figshare.com/articles/BirdsongRecognition/3470165'
  dev_url: https://github.com/NickleDave/birdsong-recognition-dataset
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - NickleDave
